### ISSUE TITLE
7.1.1以上无法用反射弹出toast，请问是什么原因

### ISSUE THREAD

**Issue by caifang2006cf** [xiaogaofudao/Android-Widget#1]
报了这个异常java.lang.NoSuchMethodException: show []

**Comment by xiaogaofudao** [comment]
@caifang2006cf 已经解决，多谢反馈

**Comment by caifang2006cf** [comment]
作者你好，用你新修改的还是弹不出来，会崩溃，信息如下：
FATAL EXCEPTION: main
                                                                               Process: com.android.benlailife.activity, PID: 6197
                                                                               android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
                                                                                   at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
                                                                                   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
                                                                                   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                   at android.widget.Toast$TN.handleShow(Toast.java:459)
                                                                                   at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by caifang2006cf** [comment]
试的7.1.1系统

**Comment by xiaogaofudao** [comment]
这个不好办了，我用的 as 自带的虚拟测试机。7.1.1 8.0 没问题了，现在手里没 真是设备。没法调试了

**Comment by caifang2006cf** [comment]
我用的就是as 7.1.1模拟器啊，然后报的错，emulator

**Comment by xiaogaofudao** [comment]
![tim 20170811103445](https://user-images.githubusercontent.com/9261849/29199647-26703780-7e81-11e7-9e57-1afc339e5b14.png)


这就奇怪了，我这边测试怎么是 ok 的呢

**Comment by xiaogaofudao** [comment]
你的 ABI 选的什么
![tim 20170811104146](https://user-images.githubusercontent.com/9261849/29199754-06530fda-7e82-11e7-97a7-2c3ae83692c1.png)

**Comment by caifang2006cf** [comment]
方便加我qq吗，问题聊起来方便一点，我的1090154860，我的模拟器nexus_5X_API_25

**Comment by caifang2006cf** [comment]
x86

**Comment by xiaogaofudao** [comment]
多谢提醒，已确认 targetSdkVersion 26 版本问题。改为 25 即可。
此问题抽空看能否解决

**Comment by shenxianshu** [comment]
@xiaogaofudao targetSdkVersion 26 的问题后期有解决方案吗

**Comment by xiaogaofudao** [comment]
@shenxianshu 目前没有，加验证估计就是防这个

**Comment by zimo2013** [comment]
1 android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:313)
--
2 android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
3 android.widget.Toast$TN.handleShow(Toast.java:459)
4 android.widget.Toast$TN$2.handleMessage(Toast.java:342)
5 android.os.Handler.dispatchMessage(Handler.java:102)
6 android.os.Looper.loop(Looper.java:154)
7 android.app.ActivityThread.main(ActivityThread.java:6268)
8 java.lang.reflect.Method.invoke(Native Method)
9 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
10 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)

手机环境：
Android 7.1.1,level 25 
360 1605 A01
targetSdkVersion 25

目前发现7.1.1有这问题
@xiaogaofudao

**Comment by huangjinhong** [comment]
1 android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:313)

2 android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
3 android.widget.Toast$TN.handleShow(Toast.java:459)
4 android.widget.Toast$TN$2.handleMessage(Toast.java:342)
5 android.os.Handler.dispatchMessage(Handler.java:102)
6 android.os.Looper.loop(Looper.java:154)
7 android.app.ActivityThread.main(ActivityThread.java:6268)
8 java.lang.reflect.Method.invoke(Native Method)
9 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
10 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)

手机环境：
Android 7.1.1,level 25
360 1605 A01
targetSdkVersion 25

目前发现7.1.1有这问题

一样遇到问题

**Comment by xiaogaofudao** [comment]
@stackzhang @huangjinhong 手里没360 这个设备啊，没办法测试，感觉应该是 360 改源码了。具体如果两位有空的话可以帮忙测试修改下这个bug。不胜感激

**Comment by zimo2013** [comment]
# main(1)
android.view.WindowManager$BadTokenException
Unable to add window -- window android.view.ViewRootImpl$W@2a5c0e6 has already been added

android.view.ViewRootImpl.setView(ViewRootImpl.java:703)
--
2 android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:344)
3 android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
4 android.widget.Toast$TN.handleShow(Toast.java:462)
5 android.widget.Toast$TN$2.handleMessage(Toast.java:345)
6 android.os.Handler.dispatchMessage(Handler.java:102)
7 android.os.Looper.loop(Looper.java:160)
8 android.app.ActivityThread.main(ActivityThread.java:6207)
9 java.lang.reflect.Method.invoke(Native Method)
10 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
11 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)


小米 MI 5C
Android 7.1.2,level 25
XiaoMi/MIUI CPU架构：arm64-v8a
目前发现有VIVO、小米、360手机 都是25出现的
@xiaogaofudao 
暂时解决办法 判断>=25系统Toast

**Comment by huangjinhong** [comment]
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@565e533 has already been added
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:726)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:347)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
       at android.widget.Toast$TN.handleShow(Toast.java:461)
       at android.widget.Toast$TN$2.handleMessage(Toast.java:344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6365)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

小米 MI6    ----> Android7.1.1
小米 MIX 2   -----> Android7.1.1
锤子：OD10360 、OD105  ------> andorid 7.1.1
魅族：PRO 6s 和 PRO 6------>andorid7.1.1

也发现问题

**Comment by huangjinhong** [comment]
应该是概率性出现的

**Comment by zimo2013** [comment]
后台这个bug一堆，但是自己测试却没有发现问题，所有7.1.1以上就不用 了 @huangjinhong

**Comment by huangjinhong** [comment]
我也是无法复现 @stackzhang

**Comment by guohaiyang1992** [comment]
7.1.1 仍崩溃 target 26  崩溃信息是token null is not valid; is your activity running?，我看了下源码，应该是7.1.1 修改了show 方法，需要传入token ，这个token 是生成的不可以传null 。。 源码里面每次创建和销毁都对这个token 做了处理，正在着手解决看看能不能生成token
